version: "3.1"

name: cqrs_test

services:
  nats:
    image: nats:2.9-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - "./nats/nats-server.conf:/etc/nats/nats-server.conf"
